# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NeKZ5Vm8+CILRsRl/V3ijsrpbShQNUpvibGEIbAPR5+i5xSUfxVsJslUJTsQ+/pptgfxxzD4Lhu7W1nsVIGtEn5bs8g+3qX7IWiJnK+DlqTnf3Z91pxJjTdCkr1NHlTwAQbZRcBDqH0oS+rPeH/4/itmmlQ5wMmQjkrbf5fpvmjMvqMnFOJbwVuLxGCy2r3ldF1iORpka77LvnCdYz8Xy2CyxaOUMUSZZUag4tpUQqh5NknhSv5pt01LlHhE6BpcDl6u6wafv723BEYbfTpX/HAd9iXcKahdD41+TxYiy3KANzPgXWgEmXF8MEb/BNDMZbxiEmSbawbHQ03s5h81vt0NL9I+vkT6KlkEMfV0knKlBVqbNKJ1xZil7FMkOdHEJUqiDcYH+q4bMXCxMwWHvmlUcIcGhwfLYbGwZ46JA3hYBIj9se75fhQ7vpvmyO8x0aDN2XTtunUKrHdp3Q0aZYNZAdGdT1W8DNvho49sT6FladWridNE2dehlTUOB7yjkxSN8NcdMvH9wtuI68WEEQl9xnwyuLBbGM0Q4wcYOu2OawOjMiLZHEzB/pBiPGq5xXnxx+OwSpCHZIKnNDHtFEShCw6e0ubiWIQW86kG9ZzYFsF64AflqbUe8jTWE86mMD2rdi0+hd5a1c/cZHANIDWkZZDv4C1+gEViGtYZOAE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
