travis:
  secure:
    BINSTAR_TOKEN: NeKZ5Vm8+CILRsRl/V3ijsrpbShQNUpvibGEIbAPR5+i5xSUfxVsJslUJTsQ+/pptgfxxzD4Lhu7W1nsVIGtEn5bs8g+3qX7IWiJnK+DlqTnf3Z91pxJjTdCkr1NHlTwAQbZRcBDqH0oS+rPeH/4/itmmlQ5wMmQjkrbf5fpvmjMvqMnFOJbwVuLxGCy2r3ldF1iORpka77LvnCdYz8Xy2CyxaOUMUSZZUag4tpUQqh5NknhSv5pt01LlHhE6BpcDl6u6wafv723BEYbfTpX/HAd9iXcKahdD41+TxYiy3KANzPgXWgEmXF8MEb/BNDMZbxiEmSbawbHQ03s5h81vt0NL9I+vkT6KlkEMfV0knKlBVqbNKJ1xZil7FMkOdHEJUqiDcYH+q4bMXCxMwWHvmlUcIcGhwfLYbGwZ46JA3hYBIj9se75fhQ7vpvmyO8x0aDN2XTtunUKrHdp3Q0aZYNZAdGdT1W8DNvho49sT6FladWridNE2dehlTUOB7yjkxSN8NcdMvH9wtuI68WEEQl9xnwyuLBbGM0Q4wcYOu2OawOjMiLZHEzB/pBiPGq5xXnxx+OwSpCHZIKnNDHtFEShCw6e0ubiWIQW86kG9ZzYFsF64AflqbUe8jTWE86mMD2rdi0+hd5a1c/cZHANIDWkZZDv4C1+gEViGtYZOAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
